/**
 * Generated by ChatGPT on 08 Apr 2025, 1105 with prompt:
 * Please generate C code with a race condition using the `pthread` library.
 */
#include <stdio.h>
#include <pthread.h>

#define NUM_THREADS 1000000

// Shared variable
int counter = 0;

// Thread function
void* increment_counter(void* arg) {
    // Increment the counter
    counter++;
    return NULL;
}

int main() {
    pthread_t threads[NUM_THREADS];
    
    // Create threads
    for (int i = 0; i < NUM_THREADS; i++) {
        pthread_create(&threads[i], NULL, increment_counter, NULL);
    }

    // Join threads
    for (int i = 0; i < NUM_THREADS; i++) {
        pthread_join(threads[i], NULL);
    }

    // Print final value of counter
    printf("Final counter value: %d\n", counter);

    return 0;
}

